#![forbid(unsafe_code)]

use std::{collections::{BTreeMap,HashMap,HashSet},fs::{self,File,OpenOptions},io::{Read,Seek,SeekFrom,Write},path::{Path,PathBuf},sync::Mutex};
use chrono::Utc;
use ed25519_dalek::{Signature,Signer,SigningKey,VerifyingKey};
use serde::{Deserialize,Serialize};
use serde_json::Value;
use sha2::{Digest,Sha256};
use thiserror::Error;
use uuid::Uuid;

const PREVIEW_TTL_MS:i64=10*60*1000;
const BUNDLE_TTL_MS:i64=30*60*1000;
pub const MAX_CHUNK_BYTES:u32=256*1024;
const MAX_SECTION_BYTES:usize=4*1024*1024;
const MAX_BUNDLE_BYTES:u64=32*1024*1024;
const PROOF_SCHEMA:&str="aethercore.support-proof.v1";
const MANIFEST_SCHEMA:&str="aethercore.support-manifest.v1";
const PROOF_KEY_KIND:&str="installation-ed25519";
const PROOF_CLAIM:&str="Tamper-evident support bundle generated by this AetherCore installation; not a vendor or hardware attestation.";
const MAX_ACTIVE_PREVIEWS_TOTAL:usize=8;
const MAX_ACTIVE_BUNDLES_TOTAL:usize=8;

#[derive(Debug,Error)]
pub enum SupportBundleError{
    #[error("support preview is unavailable or expired")] PreviewUnavailable,
    #[error("support bundle is unavailable or expired")] BundleUnavailable,
    #[error("support bundle owner mismatch")] Ownership,
    #[error("support section is too large")] SectionTooLarge,
    #[error("support bundle exceeds the protected size limit")] BundleTooLarge,
    #[error("too many support export objects are active")] ResourceLimit,
    #[error("invalid support bundle structure: {0}")] InvalidArchive(&'static str),
    #[error("support bundle proof signature is invalid")] InvalidProof,
    #[error("support bundle payload hash mismatch")] HashMismatch,
    #[error("filesystem error: {0}")] Io(#[from]std::io::Error),
    #[error("json error: {0}")] Json(#[from]serde_json::Error),
}

#[derive(Clone,Debug)]
pub struct SupportSection{pub file_name:String,pub display_key:String,pub value:Value}

#[derive(Clone,Debug,Default,Serialize,Deserialize,PartialEq,Eq)]
#[serde(rename_all="camelCase")]
pub struct PrivacyReport{pub user_path_redactions:u32,pub account_identifier_redactions:u32,pub hardware_serial_redactions:u32,pub email_redactions:u32}
impl PrivacyReport{fn add(&mut self,other:&Self){self.user_path_redactions=self.user_path_redactions.saturating_add(other.user_path_redactions);self.account_identifier_redactions=self.account_identifier_redactions.saturating_add(other.account_identifier_redactions);self.hardware_serial_redactions=self.hardware_serial_redactions.saturating_add(other.hardware_serial_redactions);self.email_redactions=self.email_redactions.saturating_add(other.email_redactions);}}

#[derive(Clone,Debug,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct SupportPreviewSection{pub file_name:String,pub display_key:String,pub size_bytes:u64}
#[derive(Clone,Debug,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct SupportPreview{pub preview_id:String,pub expires_unix_ms:i64,pub sections:Vec<SupportPreviewSection>,pub privacy:PrivacyReport,pub estimated_size_bytes:u64}
#[derive(Clone,Debug,Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
pub struct SupportBundleReady{pub bundle_id:String,pub file_name:String,pub size_bytes:u64,pub sha256:String,pub public_key_hex:String,pub public_key_fingerprint_sha256:String,pub expires_unix_ms:i64}
#[derive(Clone,Debug)]
pub struct SupportChunk{pub offset:u64,pub bytes:Vec<u8>,pub eof:bool,pub total_size:u64}

#[derive(Clone)]
struct SanitizedFile{path:String,display_key:String,bytes:Vec<u8>}
struct PreviewRecord{owner:String,preview:SupportPreview,created_unix_ms:i64,files:Vec<SanitizedFile>}
#[derive(Default)]
struct PreviewState{ready:HashMap<String,PreviewRecord>,preparing_owners:HashSet<String>}
struct BundleRecord{owner:String,ready:SupportBundleReady,path:PathBuf}
#[derive(Default)]
struct BundleState{ready:HashMap<String,BundleRecord>,preparing_owners:HashSet<String>}

#[derive(Serialize,Deserialize)]
struct ManifestFile{path:String,size_bytes:u64,sha256:String}
#[derive(Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
struct BundleManifest{schema:String,created_unix_ms:i64,files:Vec<ManifestFile>,payload_root_sha256:String}
#[derive(Serialize,Deserialize)]
#[serde(rename_all="camelCase")]
struct BundleProof{schema:String,key_kind:String,public_key_hex:String,manifest_sha256:String,signature_hex:String,claim:String}

pub struct SupportBundleEngine{staging_root:PathBuf,key_path:PathBuf,key_lock:Mutex<()>,previews:Mutex<PreviewState>,bundles:Mutex<BundleState>,fixed_key:Option<[u8;32]>}

impl SupportBundleEngine{
    pub fn new(data_root:&Path)->Result<Self,SupportBundleError>{let staging=data_root.join("support-staging");fs::create_dir_all(&staging)?;let engine=Self{staging_root:staging,key_path:data_root.join("state").join("support-signing.key"),key_lock:Mutex::new(()),previews:Mutex::new(PreviewState::default()),bundles:Mutex::new(BundleState::default()),fixed_key:None};engine.cleanup_staging();Ok(engine)}
    #[cfg(test)] pub fn with_test_key(root:&Path,key:[u8;32])->Self{let _=fs::create_dir_all(root);Self{staging_root:root.into(),key_path:root.join("unused.key"),key_lock:Mutex::new(()),previews:Mutex::new(PreviewState::default()),bundles:Mutex::new(BundleState::default()),fixed_key:Some(key)}}

    pub fn create_preview(&self,owner:&str,sections:Vec<SupportSection>)->Result<SupportPreview,SupportBundleError>{
        self.cleanup_expired();
        self.reserve_preview(owner)?;
        let result=(||{
            let mut files=Vec::new();let mut total=0u64;let mut privacy=PrivacyReport::default();
            for section in sections{if !safe_file_name(&section.file_name){return Err(SupportBundleError::InvalidArchive("unsafe section name"))}let(mut value,report)=sanitize_value(section.value);privacy.add(&report);value=canonical_value(value);let bytes=serde_json::to_vec_pretty(&value)?;if bytes.len()>MAX_SECTION_BYTES{return Err(SupportBundleError::SectionTooLarge)}total=total.saturating_add(bytes.len() as u64);files.push(SanitizedFile{path:section.file_name,display_key:section.display_key,bytes});}
            files.sort_by(|a,b|a.path.cmp(&b.path));if total>MAX_BUNDLE_BYTES{return Err(SupportBundleError::BundleTooLarge)}
            let created=now();
            let preview=SupportPreview{preview_id:Uuid::new_v4().to_string(),expires_unix_ms:created+PREVIEW_TTL_MS,sections:files.iter().map(|f|SupportPreviewSection{file_name:f.path.clone(),display_key:f.display_key.clone(),size_bytes:f.bytes.len() as u64}).collect(),privacy,estimated_size_bytes:total.saturating_add(16*1024)};
            let mut previews=self.previews.lock().unwrap_or_else(|p|p.into_inner());
            if !previews.preparing_owners.remove(owner){return Err(SupportBundleError::ResourceLimit)}
            previews.ready.insert(preview.preview_id.clone(),PreviewRecord{owner:owner.into(),preview:preview.clone(),created_unix_ms:created,files});
            Ok(preview)
        })();
        if result.is_err(){self.release_preview(owner);}
        result
    }

    fn reserve_preview(&self,owner:&str)->Result<(),SupportBundleError>{
        let mut previews=self.previews.lock().unwrap_or_else(|p|p.into_inner());
        if previews.preparing_owners.contains(owner){return Err(SupportBundleError::ResourceLimit)}
        // Replacing an owner's preview retires the old copy before building the new sanitized copy,
        // so retained + in-progress preview memory remains bounded by the same global quota.
        previews.ready.retain(|_,record|record.owner!=owner);
        let occupied=previews.ready.len().saturating_add(previews.preparing_owners.len());
        if occupied>=MAX_ACTIVE_PREVIEWS_TOTAL{return Err(SupportBundleError::ResourceLimit)}
        previews.preparing_owners.insert(owner.to_owned());
        Ok(())
    }

    fn release_preview(&self,owner:&str){
        self.previews.lock().unwrap_or_else(|p|p.into_inner()).preparing_owners.remove(owner);
    }

    pub fn prepare(&self,owner:&str,preview_id:&str)->Result<SupportBundleReady,SupportBundleError>{
        self.cleanup_expired();
        let record={
            let previews=self.previews.lock().unwrap_or_else(|p|p.into_inner());
            let value=previews.ready.get(preview_id).ok_or(SupportBundleError::PreviewUnavailable)?;
            if value.owner!=owner{return Err(SupportBundleError::Ownership)}
            PreviewRecord{owner:value.owner.clone(),preview:value.preview.clone(),created_unix_ms:value.created_unix_ms,files:value.files.clone()}
        };
        self.reserve_preparation(owner)?;
        let result=(||{
            let signing=self.load_or_create_key()?;
            let (archive,public)=build_archive(&record.files,record.created_unix_ms,&signing)?;
            if archive.len() as u64>MAX_BUNDLE_BYTES{return Err(SupportBundleError::BundleTooLarge)}
            let bundle_id=Uuid::new_v4().to_string();
            let file_name=format!("AetherCore-Support-{}.aetherdiag",record.created_unix_ms.max(0));
            let path=self.staging_root.join(format!("{bundle_id}.aetherdiag"));
            write_atomic(&path,&archive)?;
            let public_key_hex=hex::encode(public);
            let public_key_fingerprint_sha256=hex::encode(Sha256::digest(public));
            let ready=SupportBundleReady{bundle_id:bundle_id.clone(),file_name,size_bytes:archive.len() as u64,sha256:hex::encode(Sha256::digest(&archive)),public_key_hex,public_key_fingerprint_sha256,expires_unix_ms:now()+BUNDLE_TTL_MS};
            let mut bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());
            if !bundles.preparing_owners.remove(owner){
                let _=fs::remove_file(&path);
                return Err(SupportBundleError::ResourceLimit)
            }
            bundles.ready.insert(bundle_id,BundleRecord{owner:owner.into(),ready:ready.clone(),path});
            Ok(ready)
        })();
        if result.is_err(){self.release_preparation(owner);}
        result
    }

    fn reserve_preparation(&self,owner:&str)->Result<(),SupportBundleError>{
        let mut bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());
        let owner_active=bundles.preparing_owners.contains(owner)||bundles.ready.values().any(|record|record.owner==owner);
        let occupied=bundles.ready.len().saturating_add(bundles.preparing_owners.len());
        if owner_active||occupied>=MAX_ACTIVE_BUNDLES_TOTAL{return Err(SupportBundleError::ResourceLimit)}
        bundles.preparing_owners.insert(owner.to_owned());
        Ok(())
    }

    fn release_preparation(&self,owner:&str){
        self.bundles.lock().unwrap_or_else(|p|p.into_inner()).preparing_owners.remove(owner);
    }

    pub fn read_chunk(&self,owner:&str,bundle_id:&str,offset:u64,max_bytes:u32)->Result<SupportChunk,SupportBundleError>{
        self.cleanup_expired();if max_bytes==0||max_bytes>MAX_CHUNK_BYTES{return Err(SupportBundleError::InvalidArchive("invalid chunk size"))}let(record_path,total)={let bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());let record=bundles.ready.get(bundle_id).ok_or(SupportBundleError::BundleUnavailable)?;if record.owner!=owner{return Err(SupportBundleError::Ownership)}(record.path.clone(),record.ready.size_bytes)};if offset>total{return Err(SupportBundleError::InvalidArchive("offset beyond bundle"))}
        let mut file=File::open(record_path)?;file.seek(SeekFrom::Start(offset))?;let count=((total-offset).min(max_bytes as u64)) as usize;let mut bytes=vec![0u8;count];file.read_exact(&mut bytes)?;Ok(SupportChunk{offset,bytes,eof:offset.saturating_add(count as u64)>=total,total_size:total})
    }

    pub fn ready_for_owner(&self,owner:&str,bundle_id:&str)->Result<SupportBundleReady,SupportBundleError>{self.cleanup_expired();let bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());let record=bundles.ready.get(bundle_id).ok_or(SupportBundleError::BundleUnavailable)?;if record.owner!=owner{return Err(SupportBundleError::Ownership)}Ok(record.ready.clone())}

    pub fn discard(&self,owner:&str,bundle_id:&str)->Result<(),SupportBundleError>{
        let path={
            let bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());
            let record=bundles.ready.get(bundle_id).ok_or(SupportBundleError::BundleUnavailable)?;
            if record.owner!=owner{return Err(SupportBundleError::Ownership)}
            record.path.clone()
        };
        match fs::remove_file(&path){Ok(())=>{},Err(error)if error.kind()==std::io::ErrorKind::NotFound=>{},Err(error)=>return Err(error.into())}
        let mut bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());
        if bundles.ready.get(bundle_id).is_some_and(|record|record.owner==owner&&record.path==path){bundles.ready.remove(bundle_id);}
        Ok(())
    }

    fn load_or_create_key(&self)->Result<SigningKey,SupportBundleError>{if let Some(key)=self.fixed_key{return Ok(SigningKey::from_bytes(&key))}let _guard=self.key_lock.lock().unwrap_or_else(|p|p.into_inner());if let Ok(bytes)=fs::read(&self.key_path){if bytes.len()==32{let mut raw=[0u8;32];raw.copy_from_slice(&bytes);return Ok(SigningKey::from_bytes(&raw))}}
        if let Some(parent)=self.key_path.parent(){fs::create_dir_all(parent)?}let raw: [u8;32]=rand::random();let temporary=self.key_path.with_extension("key-new");{let mut options=OpenOptions::new();options.write(true).create_new(true);let mut file=match options.open(&temporary){Ok(v)=>v,Err(e)if e.kind()==std::io::ErrorKind::AlreadyExists=>{let _=fs::remove_file(&temporary);OpenOptions::new().write(true).create_new(true).open(&temporary)?},Err(e)=>return Err(e.into())};file.write_all(&raw)?;file.sync_all()?;}match fs::rename(&temporary,&self.key_path){Ok(())=>{},Err(_)if self.key_path.is_file()=>{let _=fs::remove_file(&temporary);let bytes=fs::read(&self.key_path)?;if bytes.len()!=32{return Err(SupportBundleError::InvalidArchive("support signing key length"))}let mut key=[0u8;32];key.copy_from_slice(&bytes);return Ok(SigningKey::from_bytes(&key))},Err(e)=>return Err(e.into())}Ok(SigningKey::from_bytes(&raw))}
    fn cleanup_expired(&self){
        let current=now();
        self.previews.lock().unwrap_or_else(|p|p.into_inner()).ready.retain(|_,v|v.preview.expires_unix_ms>=current);
        let expired:Vec<(String,PathBuf)>={
            let bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());
            bundles.ready.iter().filter(|(_,v)|v.ready.expires_unix_ms<current).map(|(id,v)|(id.clone(),v.path.clone())).collect()
        };
        let mut removed=Vec::new();
        for(id,path)in expired{
            match fs::remove_file(&path){Ok(())=>removed.push((id,path)),Err(error)if error.kind()==std::io::ErrorKind::NotFound=>removed.push((id,path)),Err(_)=>{}}
        }
        if !removed.is_empty(){
            let mut bundles=self.bundles.lock().unwrap_or_else(|p|p.into_inner());
            for(id,path)in removed{if bundles.ready.get(&id).is_some_and(|record|record.path==path){bundles.ready.remove(&id);}}
        }
    }
    fn cleanup_staging(&self){if let Ok(entries)=fs::read_dir(&self.staging_root){for entry in entries.flatten(){let _=fs::remove_file(entry.path());}}}
}

fn sanitize_value(value:Value)->(Value,PrivacyReport){fn walk(value:Value,key:Option<&str>,report:&mut PrivacyReport)->Value{match value{Value::Object(map)=>{let mut out=serde_json::Map::new();for(k,v)in map{let lower=k.to_ascii_lowercase();if is_account_key(&lower){report.account_identifier_redactions=report.account_identifier_redactions.saturating_add(1);out.insert(k,Value::String("<redacted-account>".into()));continue}if is_serial_key(&lower){report.hardware_serial_redactions=report.hardware_serial_redactions.saturating_add(1);out.insert(k,Value::String("<redacted-hardware-serial>".into()));continue}out.insert(k.clone(),walk(v,Some(&k),report));}Value::Object(out)},Value::Array(values)=>Value::Array(values.into_iter().map(|v|walk(v,key,report)).collect()),Value::String(s)=>Value::String(sanitize_string(&s,report)),other=>other}}
    let mut report=PrivacyReport::default();let value=walk(value,None,&mut report);(value,report)}
fn is_account_key(key:&str)->bool{matches!(key,"ownerprincipalkey"|"owner_principal_key"|"usersid"|"user_sid"|"authenticationid"|"authentication_id"|"accountname"|"account_name"|"username"|"user_name"|"sessionid"|"session_id")}
fn is_serial_key(key:&str)->bool{matches!(key,"serialnumber"|"serial_number"|"hardwareserial"|"hardware_serial")}
#[cfg(feature="fuzzing")]
pub fn fuzz_sanitize_text(value: &str) -> (String, PrivacyReport) {
    let mut report = PrivacyReport::default();
    let sanitized = sanitize_string(value, &mut report);
    (sanitized, report)
}

fn sanitize_string(value:&str,report:&mut PrivacyReport)->String{let mut out=value.to_owned();for marker in ["\\Users\\","/Users/"]{loop{let lower=out.to_ascii_lowercase();let Some(pos)=lower.find(&marker.to_ascii_lowercase())else{break};let name_start=pos+marker.len();let rest=&out[name_start..];let end=rest.find(|c: char| c == '\\' || c == '/').unwrap_or(rest.len());if end==0{break}out.replace_range(pos..name_start+end,"%USERPROFILE%");report.user_path_redactions=report.user_path_redactions.saturating_add(1);}}
    out=redact_tokens(&out,|c|c.is_ascii_alphanumeric()||matches!(c,'.'|'_'|'%'|'+'|'-'|'@'),looks_like_email,"<redacted-email>",&mut report.email_redactions);
    out=redact_tokens(&out,|c|c=='S'||c.is_ascii_digit()||c=='-',looks_like_sid,"<redacted-sid>",&mut report.account_identifier_redactions);out}
fn redact_tokens(value:&str,allowed:impl Fn(char)->bool,predicate:impl Fn(&str)->bool,replacement:&str,count:&mut u32)->String{let mut output=String::with_capacity(value.len());let mut token=String::new();let flush=|token:&mut String,output:&mut String,count:&mut u32|{if !token.is_empty(){if predicate(token){output.push_str(replacement);*count=count.saturating_add(1)}else{output.push_str(token)}token.clear();}};for ch in value.chars(){if ch.is_ascii()&&allowed(ch){token.push(ch)}else{flush(&mut token,&mut output,count);output.push(ch)}}flush(&mut token,&mut output,count);output}
fn looks_like_sid(v:&str)->bool{v.starts_with("S-1-")&&v.len()>8&&v.chars().all(|c|c.is_ascii_digit()||c=='S'||c=='-')}
fn looks_like_email(v:&str)->bool{let Some(at)=v.find('@')else{return false};at>0&&v[at+1..].contains('.')&&!v.contains(' ')}
fn safe_file_name(v:&str)->bool{!v.is_empty()&&v.len()<=80&&!v.contains('/')&&!v.contains('\\')&&v.bytes().all(|b|b.is_ascii_alphanumeric()||matches!(b,b'.'|b'-'|b'_'))}
fn canonical_value(value:Value)->Value{match value{Value::Object(map)=>{let mut sorted=BTreeMap::new();for(k,v)in map{sorted.insert(k,canonical_value(v));}let mut out=serde_json::Map::new();for(k,v)in sorted{out.insert(k,v);}Value::Object(out)},Value::Array(v)=>Value::Array(v.into_iter().map(canonical_value).collect()),v=>v}}

fn build_archive(files:&[SanitizedFile],created:i64,key:&SigningKey)->Result<(Vec<u8>,[u8;32]),SupportBundleError>{let mut manifest_files=Vec::new();let mut root=Sha256::new();for file in files{let sha=hex::encode(Sha256::digest(&file.bytes));root.update(file.path.as_bytes());root.update([0]);root.update((file.bytes.len() as u64).to_le_bytes());root.update([0]);root.update(sha.as_bytes());root.update([0]);manifest_files.push(ManifestFile{path:file.path.clone(),size_bytes:file.bytes.len() as u64,sha256:sha});}let manifest=BundleManifest{schema:MANIFEST_SCHEMA.into(),created_unix_ms:created,files:manifest_files,payload_root_sha256:hex::encode(root.finalize())};let manifest_bytes=serde_json::to_vec_pretty(&manifest)?;let manifest_sha=hex::encode(Sha256::digest(&manifest_bytes));let signature=key.sign(&manifest_bytes);let proof=BundleProof{schema:PROOF_SCHEMA.into(),key_kind:PROOF_KEY_KIND.into(),public_key_hex:hex::encode(key.verifying_key().to_bytes()),manifest_sha256:manifest_sha,signature_hex:hex::encode(signature.to_bytes()),claim:PROOF_CLAIM.into()};let proof_bytes=serde_json::to_vec_pretty(&proof)?;let mut entries:Vec<(String,Vec<u8>)>=files.iter().map(|f|(f.path.clone(),f.bytes.clone())).collect();entries.push(("bundle-manifest.json".into(),manifest_bytes));entries.push(("validation-proof.json".into(),proof_bytes));entries.sort_by(|a,b|a.0.cmp(&b.0));let mut archive=Vec::new();for(name,bytes)in entries{append_tar(&mut archive,&name,&bytes)?;}archive.extend_from_slice(&[0u8;1024]);Ok((archive,key.verifying_key().to_bytes()))}

fn append_tar(out:&mut Vec<u8>,name:&str,data:&[u8])->Result<(),SupportBundleError>{if name.len()>100{return Err(SupportBundleError::InvalidArchive("tar path too long"))}let mut header=[0u8;512];header[..name.len()].copy_from_slice(name.as_bytes());write_octal(&mut header[100..108],0o644);write_octal(&mut header[108..116],0);write_octal(&mut header[116..124],0);write_octal(&mut header[124..136],data.len() as u64);write_octal(&mut header[136..148],0);header[148..156].fill(b' ');header[156]=b'0';header[257..263].copy_from_slice(b"ustar\0");header[263..265].copy_from_slice(b"00");let sum:u64=header.iter().map(|b|*b as u64).sum();write_checksum(&mut header[148..156],sum);out.extend_from_slice(&header);out.extend_from_slice(data);let padding=(512-(data.len()%512))%512;out.resize(out.len()+padding,0);Ok(())}
fn write_octal(field:&mut[u8],value:u64){field.fill(0);let width=field.len().saturating_sub(1);let text=format!("{:0width$o}",value,width=width);let bytes=text.as_bytes();let start=width.saturating_sub(bytes.len());field[start..start+bytes.len()].copy_from_slice(bytes);let last=field.len().saturating_sub(1);field[last]=0;}
fn write_checksum(field:&mut[u8],value:u64){let text=format!("{:06o}\0 ",value);field.copy_from_slice(text.as_bytes());}
fn write_atomic(path:&Path,bytes:&[u8])->Result<(),SupportBundleError>{let temporary=path.with_extension("aetherdiag-new");{let mut file=File::create(&temporary)?;file.write_all(bytes)?;file.sync_all()?;}fs::rename(temporary,path)?;Ok(())}
fn now()->i64{Utc::now().timestamp_millis()}

pub fn verify_archive(bytes:&[u8],expected_public_key_fingerprint_sha256:&str)->Result<(),SupportBundleError>{
    if bytes.len() as u64>MAX_BUNDLE_BYTES{return Err(SupportBundleError::BundleTooLarge)}
    let entries=parse_tar(bytes)?;
    let manifest_bytes=entries.get("bundle-manifest.json").ok_or(SupportBundleError::InvalidArchive("manifest missing"))?;
    let proof_bytes=entries.get("validation-proof.json").ok_or(SupportBundleError::InvalidArchive("proof missing"))?;
    let manifest:BundleManifest=serde_json::from_slice(manifest_bytes)?;
    let proof:BundleProof=serde_json::from_slice(proof_bytes)?;
    if manifest.schema!=MANIFEST_SCHEMA||proof.schema!=PROOF_SCHEMA{return Err(SupportBundleError::InvalidArchive("schema"))}
    if proof.key_kind!=PROOF_KEY_KIND||proof.claim!=PROOF_CLAIM{return Err(SupportBundleError::InvalidProof)}
    if hex::encode(Sha256::digest(manifest_bytes))!=proof.manifest_sha256{return Err(SupportBundleError::HashMismatch)}
    let key:Vec<u8>=hex::decode(&proof.public_key_hex).map_err(|_|SupportBundleError::InvalidProof)?;
    let key:[u8;32]=key.try_into().map_err(|_|SupportBundleError::InvalidProof)?;
    let actual_fingerprint=hex::encode(Sha256::digest(key));
    if expected_public_key_fingerprint_sha256.len()!=64||!actual_fingerprint.eq_ignore_ascii_case(expected_public_key_fingerprint_sha256){return Err(SupportBundleError::InvalidProof)}
    let verifier=VerifyingKey::from_bytes(&key).map_err(|_|SupportBundleError::InvalidProof)?;
    let signature:Vec<u8>=hex::decode(&proof.signature_hex).map_err(|_|SupportBundleError::InvalidProof)?;
    let signature:[u8;64]=signature.try_into().map_err(|_|SupportBundleError::InvalidProof)?;
    verifier.verify_strict(manifest_bytes,&Signature::from_bytes(&signature)).map_err(|_|SupportBundleError::InvalidProof)?;

    let mut root=Sha256::new();
    let mut expected=BTreeMap::new();
    let mut previous:Option<&str>=None;
    for file in &manifest.files{
        if !safe_file_name(&file.path)||matches!(file.path.as_str(),"bundle-manifest.json"|"validation-proof.json"){return Err(SupportBundleError::InvalidArchive("unsafe manifest path"))}
        if previous.is_some_and(|p|p>=file.path.as_str()){return Err(SupportBundleError::InvalidArchive("manifest paths not strictly sorted"))}
        previous=Some(&file.path);
        if expected.insert(file.path.as_str(),()).is_some(){return Err(SupportBundleError::InvalidArchive("duplicate manifest path"))}
        let payload=entries.get(&file.path).ok_or(SupportBundleError::InvalidArchive("payload missing"))?;
        let actual_sha=hex::encode(Sha256::digest(payload));
        if payload.len() as u64!=file.size_bytes||actual_sha!=file.sha256{return Err(SupportBundleError::HashMismatch)}
        root.update(file.path.as_bytes());root.update([0]);root.update(file.size_bytes.to_le_bytes());root.update([0]);root.update(file.sha256.as_bytes());root.update([0]);
    }
    if hex::encode(root.finalize())!=manifest.payload_root_sha256{return Err(SupportBundleError::HashMismatch)}
    if entries.len()!=manifest.files.len().saturating_add(2){return Err(SupportBundleError::InvalidArchive("unmanifested archive entry"))}
    for name in entries.keys(){if name!="bundle-manifest.json"&&name!="validation-proof.json"&&!expected.contains_key(name.as_str()){return Err(SupportBundleError::InvalidArchive("unmanifested archive entry"))}}
    Ok(())
}
fn valid_tar_checksum(header:&[u8])->bool{if header.len()!=512{return false}let field=&header[148..156];let digits:Vec<u8>=field.iter().copied().skip_while(|b|*b==b' '||*b==0).take_while(|b|matches!(*b,b'0'..=b'7')).collect();if digits.is_empty(){return false}let text=match std::str::from_utf8(&digits){Ok(v)=>v,Err(_)=>return false};let expected=match u64::from_str_radix(text,8){Ok(v)=>v,Err(_)=>return false};let actual:u64=header.iter().enumerate().map(|(i,b)|if (148..156).contains(&i){b' ' as u64}else{*b as u64}).sum();actual==expected}
fn parse_tar(bytes:&[u8])->Result<HashMap<String,Vec<u8>>,SupportBundleError>{
    if bytes.len() as u64>MAX_BUNDLE_BYTES{return Err(SupportBundleError::BundleTooLarge)}
    let mut out=HashMap::new();let mut pos=0usize;let mut saw_terminator=false;
    while pos+512<=bytes.len(){
        let header=&bytes[pos..pos+512];
        if header.iter().all(|v|*v==0){saw_terminator=true;break}
        if !valid_tar_checksum(header){return Err(SupportBundleError::InvalidArchive("tar checksum"))}
        let typeflag=header[156];if typeflag!=0&&typeflag!=b'0'{return Err(SupportBundleError::InvalidArchive("unsupported tar entry type"))}
        let name_end=header[..100].iter().position(|v|*v==0).unwrap_or(100);
        let name=std::str::from_utf8(&header[..name_end]).map_err(|_|SupportBundleError::InvalidArchive("name utf8"))?.to_owned();
        if !safe_file_name(&name){return Err(SupportBundleError::InvalidArchive("unsafe tar path"))}
        let size_text=std::str::from_utf8(&header[124..136]).map_err(|_|SupportBundleError::InvalidArchive("size"))?.trim_matches(char::from(0)).trim();
        let size_u64=u64::from_str_radix(if size_text.is_empty(){"0"}else{size_text},8).map_err(|_|SupportBundleError::InvalidArchive("size octal"))?;
        if size_u64>MAX_SECTION_BYTES as u64&&name!="bundle-manifest.json"&&name!="validation-proof.json"{return Err(SupportBundleError::SectionTooLarge)}
        let size:usize=size_u64.try_into().map_err(|_|SupportBundleError::InvalidArchive("payload too large"))?;
        pos+=512;let end=pos.checked_add(size).ok_or(SupportBundleError::InvalidArchive("overflow"))?;if end>bytes.len(){return Err(SupportBundleError::InvalidArchive("truncated payload"))}
        if out.insert(name,bytes[pos..end].to_vec()).is_some(){return Err(SupportBundleError::InvalidArchive("duplicate tar path"))}
        pos=end;pos=pos.checked_add((512-(size%512))%512).ok_or(SupportBundleError::InvalidArchive("overflow"))?;
    }
    if !saw_terminator{return Err(SupportBundleError::InvalidArchive("tar terminator missing"))}
    if bytes[pos..].iter().any(|b|*b!=0){return Err(SupportBundleError::InvalidArchive("trailing tar data"))}
    Ok(out)
}

#[cfg(test)]
mod tests{use super::*;fn temp(name:&str)->PathBuf{std::env::temp_dir().join(format!("aether-support-{name}-{}",Uuid::new_v4()))}
    #[test]fn preview_redacts_paths_accounts_serials_and_emails(){let value=serde_json::json!({"ownerPrincipalKey":"secret","serialNumber":"SN-123","path":"C:\\Users\\Alice\\AppData\\x.log","email":"alice@example.com"});let(v,r)=sanitize_value(value);let text=v.to_string();assert!(!text.contains("Alice"));assert!(!text.contains("secret"));assert!(!text.contains("SN-123"));assert!(!text.contains("alice@example.com"));assert_eq!(r.user_path_redactions,1);assert_eq!(r.account_identifier_redactions,1);assert_eq!(r.hardware_serial_redactions,1);assert_eq!(r.email_redactions,1)}
    fn archive_bytes(engine:&SupportBundleEngine,preview_id:&str)->(Vec<u8>,String){let ready=engine.prepare("owner",preview_id).unwrap();let fingerprint=ready.public_key_fingerprint_sha256.clone();let mut bytes=Vec::new();let mut offset=0;loop{let c=engine.read_chunk("owner",&ready.bundle_id,offset,MAX_CHUNK_BYTES).unwrap();bytes.extend_from_slice(&c.bytes);offset+=c.bytes.len() as u64;if c.eof{break}}engine.discard("owner",&ready.bundle_id).unwrap();(bytes,fingerprint)}
    #[test]fn deterministic_archive_and_tamper_detection(){let root=temp("det");let engine=SupportBundleEngine::with_test_key(&root,[9u8;32]);let sections=vec![SupportSection{file_name:"diagnostics.json".into(),display_key:"support.section.diagnostics".into(),value:serde_json::json!({"b":2,"a":1})}];let preview=engine.create_preview("owner",sections).unwrap();let(mut bytes,fingerprint)=archive_bytes(&engine,&preview.preview_id);verify_archive(&bytes,&fingerprint).unwrap();let(bytes2,fingerprint2)=archive_bytes(&engine,&preview.preview_id);assert_eq!(bytes,bytes2);assert_eq!(fingerprint,fingerprint2);let payload=bytes.windows(b"\"a\": 1".len()).position(|w|w==b"\"a\": 1").unwrap();bytes[payload+5]^=1;assert!(verify_archive(&bytes,&fingerprint).is_err());let _=fs::remove_dir_all(root)}
    #[test]fn unmanifested_entry_is_rejected(){let root=temp("extra");let engine=SupportBundleEngine::with_test_key(&root,[7u8;32]);let preview=engine.create_preview("owner",vec![SupportSection{file_name:"diagnostics.json".into(),display_key:"support.section.diagnostics".into(),value:serde_json::json!({"ok":true})}]).unwrap();let(mut bytes,fingerprint)=archive_bytes(&engine,&preview.preview_id);bytes.truncate(bytes.len()-1024);append_tar(&mut bytes,"surprise.json",b"{}").unwrap();bytes.extend_from_slice(&[0u8;1024]);assert!(matches!(verify_archive(&bytes,&fingerprint),Err(SupportBundleError::InvalidArchive("unmanifested archive entry"))));let _=fs::remove_dir_all(root)}
    #[test]fn proof_claim_is_not_malleable(){let root=temp("claim");let engine=SupportBundleEngine::with_test_key(&root,[5u8;32]);let preview=engine.create_preview("owner",vec![SupportSection{file_name:"diagnostics.json".into(),display_key:"support.section.diagnostics".into(),value:serde_json::json!({"ok":true})}]).unwrap();let(mut bytes,fingerprint)=archive_bytes(&engine,&preview.preview_id);let needle=PROOF_CLAIM.as_bytes();let pos=bytes.windows(needle.len()).position(|w|w==needle).unwrap();bytes[pos]=if bytes[pos]==b'T'{b'X'}else{b'T'};assert!(matches!(verify_archive(&bytes,&fingerprint),Err(SupportBundleError::InvalidProof)));let _=fs::remove_dir_all(root)}
    #[test]fn embedded_key_is_not_a_root_of_trust(){let root=temp("key");let engine=SupportBundleEngine::with_test_key(&root,[4u8;32]);let preview=engine.create_preview("owner",vec![SupportSection{file_name:"diagnostics.json".into(),display_key:"support.section.diagnostics".into(),value:serde_json::json!({"ok":true})}]).unwrap();let(bytes,_)=archive_bytes(&engine,&preview.preview_id);assert!(matches!(verify_archive(&bytes,&"00".repeat(32)),Err(SupportBundleError::InvalidProof)));let _=fs::remove_dir_all(root)}
    #[test]fn tar_header_checksum_tampering_is_rejected(){let root=temp("tar-checksum");let engine=SupportBundleEngine::with_test_key(&root,[6u8;32]);let preview=engine.create_preview("owner",vec![SupportSection{file_name:"diagnostics.json".into(),display_key:"support.section.diagnostics".into(),value:serde_json::json!({"ok":true})}]).unwrap();let(mut bytes,fingerprint)=archive_bytes(&engine,&preview.preview_id);bytes[0]^=1;assert!(matches!(verify_archive(&bytes,&fingerprint),Err(SupportBundleError::InvalidArchive("tar checksum"))));let _=fs::remove_dir_all(root)}
    #[test]fn embedded_sid_and_email_are_redacted_inside_free_form_text(){let(v,r)=sanitize_value(serde_json::json!({"detail":"owner S-1-5-21-123-456-789-1001 contacted alice@example.com; keep HRESULT 0x80070005"}));let text=v.to_string();assert!(!text.contains("S-1-5-21-123-456-789-1001"));assert!(!text.contains("alice@example.com"));assert!(text.contains("0x80070005"));assert_eq!(r.account_identifier_redactions,1);assert_eq!(r.email_redactions,1)}
    #[test]fn one_active_bundle_per_owner_is_enforced_and_discard_releases_quota(){let root=temp("quota");let engine=SupportBundleEngine::with_test_key(&root,[8u8;32]);let p=engine.create_preview("owner",vec![SupportSection{file_name:"product.json".into(),display_key:"support.section.product".into(),value:serde_json::json!({"ok":true})}]).unwrap();let first=engine.prepare("owner",&p.preview_id).unwrap();assert!(matches!(engine.prepare("owner",&p.preview_id),Err(SupportBundleError::ResourceLimit)));engine.discard("owner",&first.bundle_id).unwrap();assert!(engine.prepare("owner",&p.preview_id).is_ok());let _=fs::remove_dir_all(root)}
        #[test]fn serial_redaction_is_non_linkable(){let(v,r)=sanitize_value(serde_json::json!({"serialNumber":123456,"hardwareSerial":"ABC"}));let text=v.to_string();assert_eq!(r.hardware_serial_redactions,2);assert_eq!(text.matches("<redacted-hardware-serial>").count(),2);assert!(!text.contains("123456"));assert!(!text.contains("ABC"));}
    #[test]
    fn preview_reservations_count_against_global_quota_before_sanitization(){
        let root=temp("preview-reservation-global");
        let engine=SupportBundleEngine::with_test_key(&root,[12u8;32]);
        for index in 0..MAX_ACTIVE_PREVIEWS_TOTAL{
            engine.reserve_preview(&format!("owner-{index}")).unwrap();
        }
        assert!(matches!(engine.reserve_preview("owner-overflow"),Err(SupportBundleError::ResourceLimit)));
        engine.release_preview("owner-0");
        assert!(engine.reserve_preview("owner-overflow").is_ok());
        let _=fs::remove_dir_all(root);
    }

    #[test]
    fn preview_reservation_is_linearized_per_owner(){
        let root=temp("preview-reservation-owner");
        let engine=SupportBundleEngine::with_test_key(&root,[13u8;32]);
        engine.reserve_preview("owner").unwrap();
        assert!(matches!(engine.reserve_preview("owner"),Err(SupportBundleError::ResourceLimit)));
        engine.release_preview("owner");
        assert!(engine.reserve_preview("owner").is_ok());
        let _=fs::remove_dir_all(root);
    }

    #[test]
    fn preparation_reservations_count_against_global_quota_before_archive_io(){
        let root=temp("reservation-global");
        let engine=SupportBundleEngine::with_test_key(&root,[10u8;32]);
        for index in 0..MAX_ACTIVE_BUNDLES_TOTAL{
            engine.reserve_preparation(&format!("owner-{index}")).unwrap();
        }
        assert!(matches!(engine.reserve_preparation("owner-overflow"),Err(SupportBundleError::ResourceLimit)));
        engine.release_preparation("owner-0");
        assert!(engine.reserve_preparation("owner-overflow").is_ok());
        let _=fs::remove_dir_all(root);
    }

    #[test]
    fn preparation_reservation_is_linearized_per_owner(){
        let root=temp("reservation-owner");
        let engine=SupportBundleEngine::with_test_key(&root,[11u8;32]);
        engine.reserve_preparation("owner").unwrap();
        assert!(matches!(engine.reserve_preparation("owner"),Err(SupportBundleError::ResourceLimit)));
        engine.release_preparation("owner");
        assert!(engine.reserve_preparation("owner").is_ok());
        let _=fs::remove_dir_all(root);
    }

}
